obplatform/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
#    (r'^$', cache_page(apps.portal.views.index, 60*30)),
    (r'^$', 'apps.portal.views.index'),
    (r'^login/$', 'apps.portal.views.login'),
    (r'^logout/$', 'apps.users.views.auth.user_logout'),
    (r'^register/$', 'apps.users.views.auth.user_register'),
    (r'^license/$', 'apps.portal.views.license'),
    (r'^help/$', 'apps.portal.views.help'),
    
    (r'^user/(?P<object_id>\d+)/$', 'apps.users.views.views.user_detail'),
    (r'^user/(?P<object_id>\d+)/edit/$', 'apps.users.views.views.user_edit'),
    (r'^user/(?P<object_id>\d+)/book/ajax_list/$', 'apps.users.views.bookviews.user_books_list'),
    (r'^user/(?P<object_id>\d+)/book/new/$', 'apps.users.views.bookviews.user_book_edit'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/$', 'apps.users.views.bookviews.user_book_detail'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/authors/$', 'apps.users.views.bookviews.user_book_authors'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/addauthor/$', 'apps.users.views.bookviews.user_book_addauthor'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/edit/$', 'apps.users.views.bookviews.user_book_edit'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/chapters/$', 'apps.users.views.bookviews.user_book_chapters'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/deletechapters/$', 'apps.users.views.bookviews.user_chapters_delete'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/chapter/(?P<chapter_id>\d+)/$', 'apps.users.views.bookviews.user_chapter'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/chapter/(?P<chapter_id>\d+)/comments/$', 'apps.users.views.bookviews.user_chapter_comments'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/chapter/(?P<chapter_id>\d+)/deletecomment/$', 'apps.users.views.bookviews.user_chapter_delcomment'),
    (r'^user/(?P<object_id>\d+)/book/(?P<book_id>\d+)/addchapter/$', 'apps.users.views.bookviews.user_chapter'),
    (r'^user/(?P<object_id>\d+)/book/delete/$', 'apps.users.views.bookviews.user_books_delete'),
    (r'^user/(?P<object_id>\d+)/book/$', 'apps.users.views.bookviews.user_books'),
    
    (r'^booklist/$', 'apps.books.views.booklist'),
    (r'^booklist/ajax_list/$', 'apps.books.views.ajax_list'),
    (r'^book/(?P<book_id>\d+)/$', 'apps.books.views.content'),
    (r'^book/(?P<book_id>\d+)/(?P<chapter_num>[^/]+)/commentsinfo/$', 'apps.books.views.chapter_comments_info'),
    (r'^book/(?P<book_id>\d+)/(?P<chapter_num>[^/]+)/addcomment/$', 'apps.books.views.add_comment'),
    (r'^book/(?P<book_id>\d+)/(?P<chapter_num>[^/]+)/allcomments/$', 'apps.books.views.chapter_comments'),
    (r'^book/(?P<book_id>\d+)/(?P<chapter_num>[^/]+)/(?P<comment_num>[^/]+)/$', 'apps.books.views.chapter_num_comments'),
    (r'^book/(?P<book_id>\d+)/(?P<chapter_num>[^/]+)/$', 'apps.books.views.chapter'),
    
    (r'^rss/', include('apps.rss.urls')),
#    (r'^site_media/(.*)$', 'django.views.static.serve', {'document_root': settings.SITE_MEDIA}),
    (r'^site_media/(.*)$', 'utils.staticview.serve', {'document_root': settings.SITE_MEDIA, 'app_media_folder':'media'}),
    (r'^admin/', include('django.contrib.admin.urls')),
)

obplatform/apps/books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals
from django.dispatch import dispatcher

C_TEXTFORMAT = [('rst', 'reStructuredText'), ('markdown', 'MarkDown')]
class Book(models.Model):
    title = models.CharField(maxlength=100)
    slug = models.CharField(maxlength=100, default='')
    description = models.TextField()
    authors = models.ManyToManyField(User)
    createdate = models.DateTimeField(auto_now_add=True)
    modifydate = models.DateTimeField(auto_now=True)
    icon = models.ImageField(upload_to="books_icon", blank=True, null=True)
    license = models.TextField(default='')
    textformat = models.CharField(maxlength=20, choices=C_TEXTFORMAT, default='rst')
    
    class Admin:pass
    
    class Meta:
        ordering = ['-modifydate']
        
    def __unicode__(self):
        return self.title
    
    def isAuthor(self, user):
        if user.is_anonymous():
            return False
        for o in self.authors.all():
            if o.id == user.id:
                return True
        return False
    
class Chapter(models.Model):
    book = models.ForeignKey(Book)
    num = models.CharField(maxlength=20)
    title = models.CharField(maxlength=100)
    abstract = models.TextField()
    modifydate = models.DateTimeField(auto_now=True)
    content = models.TextField()
    html = models.TextField()
    comment_count = models.IntegerField(default=0)
    
    class Admin:pass
    
    class Meta:
        ordering = ['num']
        
    def __unicode__(self):
        return self.title
    
    def save(self):
        if self.book.textformat == 'rst':
            from utils.rst2html import rst2html
            self.html = rst2html(self.content)
        elif self.book.textformat == 'markdown':
            import markdown
            self.html = markdown.markdown(self.content)
        super(Chapter, self).save()

def post_save_chapter(sender, instance, signal, *args, **kwargs):
    try:
        book = Book.objects.get(id=instance.book.id)
    except Book.DoesNotExist:
        return
#    book.modifydate = datetime.datetime.now()
    book.save()
dispatcher.connect(post_save_chapter , signal=signals.post_save, sender=Chapter)
    
class CommentInfo(models.Model):
    chapter = models.ForeignKey(Chapter)
    comment_num = models.CharField(maxlength=20)
    count = models.IntegerField(default=0)

C_STATUS = ((0, 'None'), (1, 'Good'), (2, 'Bad'))
class Comment(models.Model):
    book = models.ForeignKey(Book)
    chapter = models.ForeignKey(Chapter)
    comment_num = models.CharField(maxlength=20)
    username = models.CharField(maxlength=50)
    email = models.EmailField()
    website = models.URLField(default='')
    content = models.TextField()
    html = models.TextField(default='')
    status = models.IntegerField(choices=C_STATUS, default=0)
    replay = models.TextField(default='')
    createtime = models.DateTimeField(auto_now_add=True)
    
    class Admin:pass
    
    class Meta:
        ordering = ['createtime']
        
    def __unicode__(self):
        return self.content
    
def pre_save_comment(sender, instance, signal, *args, **kwargs):
    if instance.id == None:
        try:
            info = CommentInfo.objects.get(chapter=instance.chapter, comment_num=instance.comment_num)
        except CommentInfo.DoesNotExist:
            info = CommentInfo.objects.create(chapter=instance.chapter, comment_num=instance.comment_num)
        info.count += 1
        info.save()
        try:
            chapter = Chapter.objects.get(id=instance.chapter.id)
            chapter.comment_count += 1
            chapter.save()
        except Chapter.DoesNotExists:
            pass

def post_delete_comment(sender, instance, signal, *args, **kwargs):
    if instance.id == None:
        try:
            info = CommentInfo.objects.get(chapter=instance.chapter, comment_num=instance.comment_num)
        except CommentInfo.DoesNotExist:
            return
        
        if info.count <= 1:
            info.delete()
        else:
            info.count -= 1
            info.save()
            
        try:
            chapter = Chapter.objects.get(id=instance.chapter.id)
            chapter.comment_count -= 1
            chapter.save()
        except Chapter.DoesNotExists:
            pass

dispatcher.connect(pre_save_comment , signal=signals.pre_save, sender=Comment)
dispatcher.connect(post_delete_comment , signal=signals.post_delete, sender=Comment)

obplatform/apps/books/views.py
#coding=utf-8
from apps.books.models import Book, Chapter
from utils.lib_page import Page
from apps.books.validator import AddCommentValidator
from utils import ajax
from utils.common import render_template

def booklist(request):
    user = request.user
    return render_template(request, 'books/list.html')


def _get_data(request, obj):
    if obj.icon:
        icon = '<img class="border" src="/site_media/%s" alt="%s"/>' % (obj.get_icon_url(), obj.title)
    else:
        icon = '<img class="border" src="/site_media/img/book_icon.jpg" alt="%s"/>' % obj.title
    authors = [x.username for x in obj.authors.all()]
    return ({'id':obj.id, 'icon':icon, 'title':obj.title, 
        'description':obj.description, 'author':','.join(authors),
        'modifydate':obj.modifydate.strftime("%b %d,%Y %I:%m %p")})

def ajax_list(request):
    pagenum = 10
    result = []
    objs = Book.objects.all()
    page = Page(objs, request, paginate_by=pagenum)
    for o in page.object_list:
        result.append(_get_data(request, o))
    pages = (objs.count() + pagenum - 1) / pagenum
    cur = int(request.GET.get('page', 1))
    return ajax.ajax_ok_data((cur, pages, result))

def content(request, book_id):
    book = Book.objects.get(pk=int(book_id))
    return render_template(request, 'books/content.html', {'book':book})
    
def chapter(request, book_id, chapter_num):
    book = Book.objects.get(pk=int(book_id))
    chapter = Chapter.objects.get(num=chapter_num, book=book)
    prev, next = None, None
    nexts = Chapter.objects.filter(num__gt=chapter_num, book=book)
    if nexts:
        next = nexts[0]
    prevs = Chapter.objects.filter(num__lt=chapter_num, book=book)
    if prevs:
        prev = list(prevs)[-1]
    return render_template(request, 'books/chapter.html', {'book':book, 
            'chapter':chapter, 'next':next, 'prev':prev, 'COOKIES':request.COOKIES})
    
def chapter_comments_info(request, book_id, chapter_num):
    book = Book.objects.get(pk=int(book_id))
    chapter = Chapter.objects.get(num=chapter_num, book=book)
    objs = chapter.commentinfo_set.all()
    result = {}
    def _get_data(result, obj):
        result[obj.comment_num] = obj.count
    for obj in objs:
        _get_data(result, obj)
    
    return ajax.ajax_ok(result)
    
from utils.easy_cookie import set_cookie

def add_comment(request, book_id, chapter_num):
    m = AddCommentValidator(request, book_id, chapter_num)
    f, obj = m.validate_and_save(request)
    if f:
        response = ajax.ajax_ok(message='ok')
        set_cookie(response, 'username', request.REQUEST.get('username', ''))
        set_cookie(response, 'email', request.REQUEST.get('email', ''))
        set_cookie(response, 'website', request.REQUEST.get('website', ''))
        return response
    return ajax.ajax_fail(obj, message='error')

from utils.textconvert import plaintext2html
def _get_comment_data(result, obj):
    if obj.website:
        username = '<a rel="nofollow" href="%s">%s</a>' % (obj.website, obj.username)
    else:
        username = obj.username
    status = ''
    if obj.status == 1:
        status = '<span class="thanks" title="%s">√</span>' % obj.reply
    if obj.html:
        content = obj.html
    else:
        content = plaintext2html(obj.content)

    result.append({'username':username,
        'content':content, 'status':status,
        'createtime':obj.createtime.strftime("%b %d,%Y %I:%m %p")})

def chapter_comments(request, book_id, chapter_num):
    book = Book.objects.get(pk=int(book_id))
    chapter = Chapter.objects.get(num=chapter_num, book=book)
    objs = chapter.comment_set.all()
    result = []
    for obj in objs:
        _get_comment_data(result, obj)
    
    return ajax.ajax_ok(result)
    
def chapter_num_comments(request, book_id, chapter_num, comment_num):
    book = Book.objects.get(pk=int(book_id))
    chapter = Chapter.objects.get(num=chapter_num, book=book)
    objs = chapter.comment_set.filter(comment_num=comment_num)
    result = []
    for obj in objs:
        _get_comment_data(result, obj)
    
    return ajax.ajax_ok(result)

obplatform/apps/books/templates/books/chapter.html
{% load utiltags i18n %}
{% extends "base.html" %}

{% block title %}{{ book.title }}{% pyif book.isAuthor(user) %}<a href="{{ setting.URLROOT }}/user/{{ user.id }}/book/{{ book.id }}/chapter/{{ chapter.id }}/" title="{% trans "Edit this chapter" %}"><img src="/site_media/img/pencil.gif"/></a>{% endif %}{% endblock %}

{% block subject %}{{ chapter.title }}{% endblock %}

{% block nav1 %}<a href="{{ setting.URLROOT }}/booklist/">The Open Book Platform</a>{% endblock %}

{% block nav %}<div class="nav">{% if prev %}<a href="{{ setting.URLROOT }}/book/{{ book.id }}/{{ prev.num }}/">&laquo; {{ prev.title }}</a>{% endif %} | <a href="{{ setting.URLROOT }}/book/{{ book.id }}/"> table of contents </a>| {% if next %}<a href="{{ setting.URLROOT }}/book/{{ book.id }}/{{ next.num }}/">{{ next.title }} &raquo;</a>{% endif %}</div>{% endblock %}
{% block nav_footer %}<div class="nav-footer">{% if prev %}<a href="{{ setting.URLROOT }}/book/{{ book.id }}/{{ prev.num }}/">&laquo; {{ prev.title }}</a>{% endif %} | <a href="{{ setting.URLROOT }}/book/{{ book.id }}/"> table of contents </a>| {% if next %}<a href="{{ setting.URLROOT }}/book/{{ book.id }}/{{ next.num }}/">{{ next.title }} &raquo;</a>{% endif %}</div>{% endblock %}

{% block css %}
<link href="/site_media/js/modal.css" rel="stylesheet" type="text/css" />
<link href="/site_media/js/tabs.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="/site_media/js/iresizable.js"></script>
<script type="text/javascript" src="/site_media/js/modal.js"></script>
<!-- <script type="text/javascript" src="/site_media/js/ifxslide.js"></script>
<script type="text/javascript" src="/site_media/js/ifx.js"></script> -->
<script type="text/javascript" src="/site_media/js/jquery.tabs.pack.js"></script>
<script type="text/javascript">
var ajax_url = 'commentsinfo/';
var comment_num;
function createcomments(data, fresh){
    var fresh = fresh || 'yes';
    if (fresh == 'no'){
        $('div.comment-indicator').remove();
    }
    $('.cn').each(function(){
        var id = $(this).attr('id');
        var div;
        var height = $(this).css('height');
        var top = this.offsetTop + 20;
        if (data[id]){
            div = '<div class="comment-indicator has-comments" style="height: $0;"><span>$1</span></div>'.template([height, data[id]]);
        }else{
            div = '<div class="comment-indicator" style="height: $0;"><span></span></div>'.template([$(this).css('height')]);
        }
        $(div).appendTo(this).click(function(){
            $('#highlight-floater').remove();
            $('body').append('<div id="highlight-floater" style="visibility: visible; opacity: 0.3; width: 730px; left: 135px; top: $0; height: $1;"/>'.template([top+'px', height]));
            $('#modalwindow').show();
            if (data[id]){
                $('#comments').triggerTab(2);
                $.post(id+'/', {}, function(data){
                    var result = data.evalJson();
                    if (result.response == 'ok'){
                    	var data = result.data;
                    	createcommentslist(data, $('#comment-tabs'));
                    }
                });
            }
            else
                $('#comments').triggerTab(1);
            $('input[@name="comment_num"]', '#comments').val(id);
            comment_num = id;
            var win = $('#comments').parent().parent();
            var left = $(window).width()/2 - win.width()/2;
            var t = window.scrollY + $(window).height()/2 - win.height()/2;
            win.css({'top':t+'px', 'left':left+'px'});
            $('#comments').parent().parent().show();
        });
    });
    if (fresh == 'yes'){
        $('#comments').tabs({onClick:onClick}).modal({trigger:'div.comment-indicator'}, null, unload);
    }
}

createcommentslist = function(data, o){
    var ol = $('<ol></ol>');
    $.each(data, function(){
        ol.append('<li class="comment"><dl><dt>$username <span class="meta">$createtime</span> $status</dt><dd><p>$content</p></dd></dl></li>'.template(this));
    });
    $(o).empty().append(ol);
}

onClick = function(t, o){
    if($(t).attr('tabindex') == 2){
        $.post(comment_num+'/', {}, function(data){
            var result = data.evalJson();
            if (result.response == 'ok'){
            	var data = result.data;
            	createcommentslist(data, o);
            }
        });
    }
    if($(t).attr('tabindex') == 3){
        $.post('allcomments/', {}, function(data){
            var result = data.evalJson();
            if (result.response == 'ok'){
                var data = result.data;
                createcommentslist(data, o);
            }
        });
    }
}

function unload(w){
    w.fadeOut('high');
    $('#highlight-floater').remove();
}

function handle_list(data){
	var result = data.evalJson();
	if (result.response == 'ok'){
		var data = result.data;
		createcomments(data);
	}
}

function handle_post(data){
	var result = data.evalJson();
	if (result.response == 'ok'){
		var data = result.data;
		createcomments(data, 'no');
	}
}

$(document).ready(function (){
	$.post(ajax_url, {}, handle_list);
    on_success_finish = function(obj, r){
        $.post(ajax_url, {}, handle_post);
    };
    $('#commentform').jform({trigger:'#comment-submit', 
        messageid:'#comments-message',delaytime:2000,
        'on_success_finish':on_success_finish,errortag:'span'});
});
</script>
{% endblock %}

{% block content %}
{{ chapter.html }}
{% endblock %}

{% block other %}
<div id="comments" style="display: none;">
    <ul class="anchors">
        <li><a href="#comment-tabs-form" tabindex="1"><strong>Post a comment</strong></a></li>
        <li><a href="#comment-tabs" tabindex="2"><strong>Comments on this block</strong></a></li>
        <li><a href="#comment-tabs-all" tabindex="3"><strong>All comments</strong></a></li>
    </ul>

    <div class="tab" id="comment-tabs-form">
        <div class="bd">
            <form id="commentform" method="post" action="{{ setting.URLROOT }}/book/{{ book.id }}/{{ chapter.num }}/addcomment/">
                <p>
                    <input type="hidden" value="" name="comment_num"/>
                    <label class="required">Name (required)</label>
                    <input type="text" value="{{ COOKIES.username }}" name="username"/>
                </p>
                <p>
                    <label class="required">E-mail (required; will not be displayed)</label>
                    <input type="text" value="{{ COOKIES.email }}" name="email"/>
                </p>
                <p>
                    <label>Website</label>
                    <input type="text" value="{{ COOKIES.website }}" name="website"/>
                </p>
                <p>
                    <label class="required">Comment (required)</label>
                    <textarea rows="6" cols="30" name="content"/></textarea>
                </p>
            </form>
        </div>
        <div class="ft">
            <div id="comments-message" class="" style="display:none;">Loading comments...</div>
            <div id="comments-submit-wrapper">
                <input type="submit" value="Post comment" id="comment-submit" style="visibility: visible;"/>
            </div>
        </div>
    </div>
    <div class="tab yui-ext-tabitembody comment-tabs" id="comment-tabs">
    </div>
    <div class="tab yui-ext-tabitembody comment-tabs" id="comment-tabs-all">
    </div>
    
</div>
{% endblock %}
{% block license %}{{ book.license|default:"Writedonw your license here." }}{% endblock %}

obplatform/apps/books/templates/books/content.html
{% load i18n %}
{% extends "base.html" %}
{% block title %}{{ book.title }}{% endblock %}
{% block subject %}{% trans "Table of Contents" %}  <a href="{{ setting.URLROOT }}/rss/book/{{ book.id }}/" class="rss"><img src="/site_media/img/feed.png" title="subscribe this book"/></a> <a href="{{ setting.URLROOT }}/rss/book/{{ book.id }}/comments/" class="rss"><img src="/site_media/img/feed.png" title="subscribe the comments of this book"/></a>{% endblock %}
{% block content %}
<ol class="toc">    
{% for obj in book.chapter_set.all %}
    <li>
      <span class="release-date">
          {{ obj.modifydate|date:"F j,Y" }}
      </span>
      <a href="{{ obj.num }}/" title="{{ obj.abstract }}">
          {{ obj.title }}
      </a>
      {% if obj.comment_count %}
      <span class="comment_num"> ( {{ obj.comment_count }} )</span>
      {% endif %}
    </li>
{% endfor %}
</ol>
{% endblock %}
{% block nav1 %}<a href="{{ setting.URLROOT }}/booklist/">{% trans "The Open Book Platform" %}</a>{% endblock %}
{% block license %}{% trans "The license of this book: " %}{{ book.license|default:"Writedonw your license here." }}{% endblock %}

obplatform/apps/books/templates/books/inc_book_form.html
{% load i18n %}
<form id="book_edit_form" enctype="multipart/form-data" action="edit/" method="post">
    <div class="bd">
        <p>
            <lable class="require">{% trans "Title" %}:</lable>
            <input type="text" name="title" value="{{ book.title }}"/>
        </p>
        <p>
            <lable class="require">{% trans "Slug" %}:</lable>
            <input type="text" name="slug" value="{{ book.slug }}"/>
        </p>
        <p>
            <lable class="require">{% trans "Description" %}:</lable></dt>
            <textarea rows="3" cols="40" name="description">{{ book.description }}</textarea>
        </p>
        <p>
            <lable>{% trans "License" %}:</lable>
            <textarea rows="2" cols="40" name="license">{{ book.license }}</textarea>
        </p>
        <p>
            <lable class="require">{% trans "Text Format" %}:</lable>
            <select name="textformat">
                <option value="">---------</option>
                <option value="rst" {% ifequal book.textformat "rst" %}selected{% endifequal %}>reStructureText</option>
                <option value="markdown" {% ifequal book.textformat "markdown" %}selected{% endifequal %}>MarkDown</option>
            </select>
        </p>
        <p>
            <lable>{% trans "Logo" %}:</lable>
            <input type="file" name="icon"/>
        </p>
    </div>
    <div class="ft">
        <div class="message" class="" style="display:none;">Loading comments...</div>
        <div class="submit-wrapper">
            <input type="submit" value="{% trans "Save" %}" />
        </div>
    </div>
</form>

obplatform/apps/books/templates/books/inc_chapter.html
{% load utiltags i18n %}
<script type="text/javascript">
function createtable(target, data){
    var ul = $('<ul></ul>')
    $.each(data, function(n){
        var li = $('<li>$html</li>'.template(this));
        var d = this;
        ul.append(li);
        $('.delete', li).click(function(){
            $.post('deletecomment/', {'comment_id':d['id']}, function(data){
                li.remove();
            });
        });
    });
    $(target).empty().append(ul);
}

function handle_list(data){
    var result = data.evalJson();
    if (result.response == 'ok'){
        var data = result.data;
        createtable('#comments', data);
    }
}

$(function(){
    $('#upload_form').jform();
    $.post('comments/', {}, handle_list);
});
</script>
{% catch as header %}
    <h1><a href="{{ setting.URLROOT }}/book/{{ book.id }}/{{ chapter.num }}/">{{ chapter.title }}</a></h1>
{% endcatch %}
{% catch as content %}
    <form id="upload_form" action="{{ setting.URLROOT }}/user/{{ user.id }}/book/{{ book.id }}/chapter/{{ chapter.id }}/" method="post">
        <div class="basic_form" id="upload">
			<div id="message"></div>
            <p class="blockintro">Create a new book, and fill in information:</p>
            <div class="block">
                <dl>                    <dt class="required"><lable>{% trans "Chapter Num" %}:</lable></dt>                    <dd><input type="text" name="num" value="{{ chapter.num }}"/><dd>                </dl>                <dl>
                    <dt class="required"><lable>{% trans "Title" %}:</lable></dt>
                    <dd><input type="text" size="50" name="title" value="{{ chapter.title }}"/><dd>
                </dl>
                <dl>
                    <dt><lable>{% trans "Abstract" %}:</lable></dt>
                    <dd><textarea rows="2" cols="40" name="abstract">{{ chapter.abstract|escape }}</textarea><dd>
                </dl>
                <dl>
                    <dt class="required"><lable>{% trans "Content" %}:</lable></dt>
                    <dd><textarea rows="30" cols="40" name="content">{{ chapter.content|escape }}</textarea><dd>
                </dl>
            </div>
            <div class="action">
                <input type="submit" value="{% trans "Save" %}" />
            </div>
        </div>
    </form>
{% endcatch %}
{% catch as sidebar %}
    <p><a href="{{ setting.URLROOT }}/user/{{ user.id }}/book/{{ book.id }}/" class="admin" id="delete">{% trans "Return to table of contents" %}</a></p>
    <h2>{% trans "Comments Manager" %}</h2>
    <div id="comments">{% trans "Loading" %}...{% include "utils/ajax_loading.html" %}</div>
{% endcatch %}
{% call "utils/contentframe.html" with header content sidebar %}

obplatform/apps/books/templates/books/list.html
{% load i18n %}
{% extends "base.html" %}
{% block subject %}{% trans "Book List" %} <a href="{{ setting.URLROOT }}/rss/book/" class="rss"><img src="/site_media/img/feed.png" title="subscribe booklist"/></a>{% endblock %}
{% block content %}
<div id="documents" class="booklist">{% trans "Loading..." %}{% include "utils/ajax_loading.html" %}</div>
<div id="pages"></div>
{% endblock %}
{% block js %}
<script type="text/javascript">
var ajax_url = 'ajax_list/';
function createtable(target, data){
	var table = $('<table width="100%"><tbody></tbody></table>')
	$.each(data, function(n){
		var tr = $('<tr><td width="1%">$icon</td><td><dl><dt><i>$title</i></dt><dd><p><span class="keyword">Author</span>: <span class="info">$author</span></p><p><span class="keyword">Lastest Update</span>: <span class="info">$modifydate</span></p><p class="description">$description</p></dd></dl></td></tr>'.template(this));
		table.append(tr);
		var d = this;
		tr.click(function(){
			window.location = '{{ setting.URLROOT }}/book/$id/'.template(d);
		});
	});
	$(target).empty().append(table);
//	$("tbody tr:even", target).addClass("alt");
	$("tbody tr", target)
	    .mouseover(function(){
	        $(this).addClass("over");
	    })
	    .mouseout(function(e){
	        $(this).removeClass("over");
	    });
}

function handle_list(data){
	var result = data.evalJson();
	if (result.response == 'ok'){
		var data = result.data;
		createtable('#documents', data[2]);
		$('#pages').empty().paginate(ajax_url, data[0], data[1]).append('<br style="clear:both;"/>');
		$('#pages a').click(function(){
			var href = this.href;
			$.get(href, handle_list);
			return false;
		});
	}
}

$(document).ready(function (){
	$.post(ajax_url, {}, handle_list);
});
</script>
{% endblock %}